# This is basic workflow to help you get started with Actions

name : nn

# Controls when the action will run.

on:
  push:
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install . 
          pip install -r requirements.txt
      - name: Run unit tests
        run: python -m pytest -vv test/test*py